In [1]:
%matplotlib qt

In [2]:
from __future__ import division
from matplotlib import pyplot as plt
import math
import numpy as np

In [3]:
def find_nearest(array,value):
    idx = (np.abs(array-value)).argmin()
    return idx

In [4]:
def find_nearests(array,values):
    idx = []
    for val in values:
        idx.append((np.abs(array-val)).argmin())
    return idx

In [5]:
def link_points_with_line(first_point = None, second_point = None):
    a = first_point[0] , second_point[0]
    b = first_point[1] , second_point[1]
    return a,b

def plot_line_between_points(first_point = None, second_point = None):
    link_points = link_points_with_line(first_point, second_point)
    return plt.plot(link_points[0], link_points[1])

In [6]:
plt.plot()

[]

In [7]:
%pylab

Using matplotlib backend: Qt4Agg
Populating the interactive namespace from numpy and matplotlib


In [8]:
plt.close()
#plt.plot([1,2],[1,2],color='k',marker='o')

## Une fonction convexe

In [9]:
def convex_tax_func(income = None):
    return  ((income/3150) **3)

In [10]:
a = np.array(range(0,10**5))
taxe_vector = np.apply_along_axis(convex_tax_func,0, a)

In [11]:
plt.plot(taxe_vector)

In [12]:
plt.xlabel("Income")
plt.ylabel("Tax")

Two monthly wages :

In [13]:
markers_on = [30000, 90000 ]

In [14]:

plt.plot(a[markers_on], taxe_vector[markers_on], 'gs', alpha = 0.8)

ax = plt.axes()


In [15]:

liste = ax.xaxis.get_ticklabels()
ax.xaxis.set_ticklabels([0,20000,40000,60000,80000,10000])
#print liste.count()
ax.plot()

[]

In [16]:
#VERTICAL DASH LINE
plt.vlines(a[markers_on][0], 0, taxe_vector[markers_on][0], linestyles='dashed')
plt.vlines(a[markers_on][1], 0, taxe_vector[markers_on][1], linestyles='dashed')
#POINTS
#TODO : mettre y_1 et Y_2 en ticks plutôt qu'en plt.text 
#plt.text( a[markers_on][0]-600, taxe_vector[markers_on][0]+800, r'$y_1$',fontsize=15)
#plt.text( a[markers_on][1]-2600, taxe_vector[markers_on][1]+800, r'$y_2$',fontsize=15)

text = plt.text(29000, -1000, r'$y_1$', weight = 'bold' )
text2 = plt.text(89000, -1000, r'$y_2$', weight = 'bold' )



In [17]:
#averge tax on a monthly basis
plt.plot(a[markers_on].tolist()
         ,
         taxe_vector[markers_on].tolist()
         ,'g', alpha = 0.8
        )

/usr/local/lib/python2.7/site-packages/matplotlib/collections.py:590: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == str('face'):


In [18]:
d = a[markers_on].sum()/2
e = taxe_vector[markers_on].sum()/2
monthly_average = d,e
plt.plot(d,e, 'gs', alpha = 0.9)

In [19]:
plt.rc('text', usetex=True)
plt.rc('font', family='serif')

#plt.text(d, e, r"$frac{-e^{i\pi}}{2^n}$!")
#plt.text(d -4000, e+4000,r"$\frac{y_1 + y_2}{2}$", fontsize=15)


liste = ax.xaxis.get_ticklabels()
ax.xaxis.set_ticklabels([0,20000,40000,r"$\frac{y_1 + y_2}{2}$",80000,10000])
ax.xaxis.set_ticks
#print liste.count()
ax.plot()


plt.vlines(d, 0, e, linestyles='dashed')

In [20]:
#fist_point = [1,1]
#second_point = [3,3]
#plt.plot([1,3],[1,2],color='k',marker='o')

In [21]:
#plot_line_between_points(fist_point, second_point)

In [22]:
#link_points_with_line(fist_point, second_point)

In [23]:
middle = (taxe_vector[markers_on[0]]+taxe_vector[markers_on[1]])//2

In [24]:
#average tax on a annual one
plt.plot(a[(markers_on[0]+markers_on[1])//2], 
         taxe_vector[(markers_on[0]+markers_on[1])//2], 'rD') 

In [25]:
annual_average = a[(markers_on[0]+markers_on[1])/2], taxe_vector[(markers_on[0]+markers_on[1])/2]
#plot_line_between_points(monthly_average, annual_average)

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:1: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  if __name__ == '__main__':


In [26]:
plt.text( 56500, middle, r'$\bar{G_t}$', weight = 'bold' )
plt.text( 56500, 6700, r'$\bar{G}$', weight = 'bold' )

In [27]:
plt.annotate(
    '', xy=annual_average, xycoords='data',
    xytext=monthly_average, textcoords='data',
    arrowprops= dict(facecolor='black', width=0.03))#{'arrowstyle': '<->'}) #TODO : find how to change arrowstyle width

#plt.annotate(
#    'D = 1', xy=annual_average, xycoords='data',
#    xytext=monthly_average, textcoords='offset points')



In [28]:
#plt.text( 60000+100, middle-2000, r'$\bar{G}- \sum G_t$')
plt.text( 60000+200, middle-2050, r'$\bar{G}- \bar{G_t}$', weight = 'bold' )


In [29]:
(markers_on[0]+markers_on[1])/2

60000.0

In [30]:
plt.plot(0,0,alpha = 0, label=r'$\bar{G} = \frac{G(\sum{y_t})}{T}$')
plt.plot(0,0,alpha = 0, label=r'$\bar{G_t} = \frac{\sum{\frac{G(Ty_t)}{T}}}{T}$')
plt.legend(loc = 2)

In [31]:
image_number = 1
image_path = "/Users/adrienpacifico/Dropbox/These_Pacifico/Adrien_Thesis_personal_docs/Latex_docs_whith_Git_versionning/Tax_temporality/programme/Theoreme_presentation/images/"
plt.savefig(image_path+"image_graph{}".format(image_number)); image_number+=1


### Lambda (compensation)

$\lambda$ s.t ...


$\lambda = \frac{G(2y_1)+G(2y_2)}{G(y_1+y_2)}$

In [32]:
def compensation(markers_on = None):
    return (
            (convex_tax_func(income = markers_on[0]) + convex_tax_func(income = markers_on[1]))
            / 
            (2*convex_tax_func(income = (markers_on[0]+markers_on[1])/2)))

In [33]:
compensation(markers_on)

1.7500000000000004

In [34]:
compensated_points = np.apply_along_axis(convex_tax_func,0, markers_on)/compensation(markers_on)

In [35]:
compensated_points

array([   493.62148488,  13327.78009163])

In [36]:
plt.plot(a[markers_on],compensated_points, 'y*', markersize = 8)


In [37]:
plt.text( a[markers_on][1]+200, compensated_points[1]+200, r'$\frac{G(2y_2)}{2+\lambda}$', weight = 'bold' )

In [38]:
plt.text( a[markers_on][0]-9400, compensated_points[0]+200, r'$\frac{G(2y_1)}{2+\lambda}$', weight = 'bold' )

plt.annotate(
    '', xy=[a[markers_on][0]-700,compensated_points[0]-40],
    xycoords='data',
    xytext= [26660, 1458],
    textcoords='data',
    arrowprops= dict(facecolor='black', width=0.01,frac = 0.2, headwidth =4 , shrink = 0.01))

In [39]:
#text.remove()

In [40]:
#input()

In [41]:
plt.plot(a[markers_on], compensated_points, 'y')

In [42]:
image_path = "/Users/adrienpacifico/Dropbox/These_Pacifico/Adrien_Thesis_personal_docs/Latex_docs_whith_Git_versionning/Tax_temporality/programme/Theoreme_presentation/images/"
plt.savefig(image_path+"image_graph{}".format(image_number)); image_number+=1

In [43]:
np.apply_along_axis(convex_tax_func,0, markers_on)

array([   863.83759853,  23323.61516035])

In [44]:
plt.figure()

In [45]:
plt.close()

In [66]:
plt.figure()

## Utility function

In [67]:
def concave_u_func(income = None):
    return  (1 - 0.97**(income/1200))


#def concave_u_func(income = None):
#    return  income**0.4

In [68]:
def disposable_income(income = a):
    return a - np.apply_along_axis(convex_tax_func,0, a)

In [69]:
plt.plot([0,90000],[0,90000],color='k',marker='o')

In [70]:
plt.plot(a,disposable_income(a))

In [71]:
plt.close()
plt.figure()

In [72]:
a = np.array(range(0,10**5))
utility_vector = np.apply_along_axis(concave_u_func,0, a)
utility_disposable_income = np.apply_along_axis(concave_u_func,0, disposable_income(a))


In [73]:
plt.plot(a,utility_vector)

#gross income utility
plt.plot(a[markers_on], utility_vector[markers_on], 'bo', label = "Before tax")


In [74]:
utility_vector[find_nearests(utility_vector, utility_disposable_income[markers_on])]

array([ 0.52267112,  0.81592557])

In [75]:
#Taxed utility
monthly_u_loss = plt.plot(a[markers_on], utility_disposable_income[markers_on], 'gs', alpha = 0.8, label = "Sub-period tax")


In [76]:
a[markers_on]

array([30000, 90000])

In [77]:
find_nearest(utility_vector,utility_disposable_income[markers_on][1] )

66676

In [78]:
plt.plot(
         find_nearests(utility_vector, utility_disposable_income[markers_on]), 
    utility_vector[find_nearests(utility_vector, utility_disposable_income[markers_on])],'gs', alpha = 0.8)

In [79]:
find_nearests(utility_vector, utility_disposable_income[markers_on])

[29136, 66676]

In [80]:
plt.plot(find_nearests(utility_vector, utility_disposable_income[markers_on])
         ,
         utility_vector[find_nearests(utility_vector,utility_disposable_income[markers_on] )]
         ,'g', alpha = 0.8
        )

In [81]:
#plot_line_between_points(first_point = (a[markers_on][0], utility_disposable_income[markers_on][0]), second_point = (a[markers_on][0], utility_vector[markers_on][0]))
#plot_line_between_points(first_point = (a[markers_on][1], utility_disposable_income[markers_on][1]), second_point = (a[markers_on][1], utility_vector[markers_on][1]))

In [82]:
a_tax_util_index = np.array( [find_nearest(utility_vector,utility_disposable_income[markers_on][0]) , find_nearest(utility_vector,utility_disposable_income[markers_on][1] )])

In [83]:
#plot_line_between_points(first_point = (a[markers_on][0], utility_disposable_income[markers_on][0]), second_point = (a[a_tax_util_index][0], utility_vector[a_tax_util_index][0])) # TODO: dashed line
#plot_line_between_points(first_point = (a[markers_on][1], utility_disposable_income[markers_on][1]), second_point = (a[a_tax_util_index][1], utility_vector[a_tax_util_index][1])) # TODO: dashed line

In [84]:
a_tax_util_index

array([29136, 66676])

In [85]:
#plt.plot(a[a_tax_util_index].tolist()
#         ,
#         utility_vector[a_tax_util_index].tolist()
#         ,
#        )

In [86]:
d = a[a_tax_util_index].sum()/2
e = utility_vector[a_tax_util_index].sum()/2
monthly_average = d,e
plt.plot(d,e, 'gs', alpha = 0.8)
average_monthly = (d,e)

In [87]:
#TODO : Think about it mais à priori faux !
final_point_monthly = [a[find_nearest(utility_vector,e)], utility_vector[find_nearest(utility_vector,e)]]
plt.plot(a[find_nearest(utility_vector,e)], utility_vector[find_nearest(utility_vector,e)], 'go')
#plt.plot(d,utility_vector[d], 'go')

In [88]:
#plot_line_between_points(first_point = (a[find_nearest(utility_vector,e)], utility_vector[find_nearest(utility_vector,e)]), 
#                         second_point = (d,e))

In [89]:
d = a[markers_on].sum()/2
monthly_annual_tax = utility_vector[d]
monthly_d_income_a_t = a[markers_on] - monthly_annual_tax

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:2: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  from ipykernel import kernelapp as app


In [90]:
#b[60000]

In [91]:
#Annual après taxe
d = a[markers_on].sum()/2
monthly_annual_tax = taxe_vector[d]
monthly_d_income_a_t = a[markers_on] - monthly_annual_tax
monthly_u_a_t = utility_vector[find_nearests(a, monthly_d_income_a_t)]
plt.plot(a[markers_on][1],monthly_u_a_t[1], 'rD', label = 'Reference period tax')
plt.plot(a[markers_on][0],monthly_u_a_t[0], 'rD')
#plt.plot(d[1],e[1], 'ro')

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:3: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  app.launch_new_instance()


In [92]:
#projection sur axe utilité
idx = find_nearests(a, monthly_d_income_a_t)
plt.plot(a[idx][0], utility_vector[idx][0], 'rD')
plt.plot(a[idx][1], utility_vector[idx][1], 'rD')





In [93]:
#line between points
plt.plot(a[idx], utility_vector[idx], 'r')

In [94]:
plt.plot(np.mean([idx]), np.mean(utility_vector[idx]), 'rD')
average_annual = (np.mean([idx]), np.mean(utility_vector[idx]))

In [95]:
(a[idx][0] + a[idx][1])/2
np.mean(a[idx])

53089.0

In [96]:
utility_vector[np.mean(a[idx])]

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:1: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  if __name__ == '__main__':


0.74012141083962835

In [97]:
plt.plot(np.mean(a[idx]),utility_vector[np.mean(a[idx])] )

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:1: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  if __name__ == '__main__':


In [98]:
# A priori non
final_point_annual = [a[find_nearest(utility_vector,(utility_vector[idx][0] + utility_vector[idx][1])/2)],
         utility_vector[a[find_nearest(utility_vector,(utility_vector[idx][0] + utility_vector[idx][1])/2)]]]
    
plt.plot(a[find_nearest(utility_vector,(utility_vector[idx][0] + utility_vector[idx][1])/2)],
         utility_vector[a[find_nearest(utility_vector,(utility_vector[idx][0] + utility_vector[idx][1])/2)]],'rD')
#plt.plot(np.mean(a[idx]),
#        utility_vector[np.mean(a[idx])] ,'ro')


In [99]:
#line between la corde and utility func 
plt.plot([np.mean(a[idx]),np.mean(a[idx])],
        [utility_vector[np.mean(a[idx])], 
        utility_vector[np.mean(a[idx])]])

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:3: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  app.launch_new_instance()
/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:4: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


In [100]:
#average
find_nearest(a,monthly_d_income_a_t.sum()/2)

53089

In [101]:
# Faire le find nearest sur la courbe d'utilité, faire utilité moyenne

In [102]:
monthly_u_a_t = utility_vector[find_nearests(a, monthly_d_income_a_t)]; monthly_u_a_t

array([ 0.44348466,  0.87864327])

In [103]:
find_nearest(a[markers_on], monthly_d_income_a_t)

0

In [104]:
#Annual après taxe
#f = a[markers_on].sum()/2
#g =  utility_disposable_income[d]
#annual_average = d,e
#plt.plot(f,g, 'ro')

In [105]:
#plot_line_between_points(first_point = (d,e), second_point = (f,g))


In [106]:
#plt.plot(a[find_nearest(utility_vector,g)], utility_vector[find_nearest(utility_vector,g)], 'ro')

In [107]:
#plot_line_between_points(first_point = (f,g), second_point =
#                         (a[find_nearest(utility_vector,g)], utility_vector[find_nearest(utility_vector,g)]))

In [108]:
#utility loss without compensation


#plot_line_between_points(first_point = , second_point = (f,g))







In [109]:
compensation(markers_on)

1.7500000000000004

In [110]:
compensated_points

array([   493.62148488,  13327.78009163])

In [111]:
find_nearest(a[markers_on], compensated_points[1])

0

In [112]:
compensated_disposable_income = np.apply_along_axis(concave_u_func, 0, a[markers_on] - compensated_points )

In [113]:
compensated_disposable_income

array([ 0.52713756,  0.85717653])

In [114]:
plt.plot(a[markers_on],compensated_disposable_income,'y*', markersize = 8, label = "Compensated sub-period tax")

In [115]:
plt.plot(a[find_nearests(utility_vector, compensated_disposable_income)],
        compensated_disposable_income, 'y*', markersize = 8)

In [116]:
#
plt.plot(a[find_nearests(utility_vector, compensated_disposable_income)],
        compensated_disposable_income, 'y')

In [117]:
plt.plot(np.mean(a[find_nearests(utility_vector, compensated_disposable_income)]),
        np.mean(compensated_disposable_income), 'y*', markersize = 8)
average_compensated = (np.mean(a[find_nearests(utility_vector, compensated_disposable_income)]),
                       np.mean(compensated_disposable_income))

In [118]:
final_point_compensated = [find_nearest(utility_vector, np.mean(compensated_disposable_income)),np.mean(compensated_disposable_income)]

plt.plot(final_point_compensated[0],final_point_compensated[1] , 'y*', markersize = 8)

In [119]:
utility_vector[np.mean(a[find_nearests(utility_vector, compensated_disposable_income)])]

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:1: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  if __name__ == '__main__':


0.74012141083962835

In [120]:
plt.legend(numpoints=1, fontsize = 'small', loc = 4 )

#### Arrows

In [121]:
plt.text( 32700, 0.74, u'3: final average\n utility', weight = 'bold' )

In [122]:
plt.text( 90000, 0.83, r"\rbrace", weight = 'bold', fontsize = 35 )
plt.text( 92500, 0.83, u"1: utility loss \n due to tax \n in period t=2", weight = 'bold',  fontsize = 10 )

In [123]:
plt.text( 30000, 0.45, r"\rbrace", weight = 'bold', fontsize = 41 )
plt.text( 33700, 0.45, u"1: utility loss \n due to tax \n in period t=1", weight = 'bold',  fontsize = 10 )

In [124]:
print "{hello"

{hello


In [125]:
plt.annotate(
    '', xy=final_point_compensated,
    xycoords='data',
    xytext=[41530,0.73], textcoords='data',
    arrowprops= dict(facecolor='black', width=0.01,frac = 0.2, headwidth =4 , shrink = 0.01))


In [126]:
plt.annotate(
    '', xy=final_point_monthly,
    xycoords='data',
    xytext=[41530,0.73], textcoords='data',
    arrowprops= dict(facecolor='black', width=0.01,frac = 0.2, headwidth =4 , shrink = 0.01))

In [127]:
plt.annotate(
    '', xy=final_point_annual,
    xycoords='data',
    xytext=[41530,0.73], textcoords='data',
    arrowprops= dict(facecolor='black', width=0.01,frac = 0.2, headwidth =4 , shrink = 0.01))

In [128]:
plt.annotate(
    '', xy=average_annual,
    xycoords='data',
    xytext=[57000,0.58], textcoords='data',
    arrowprops= dict(facecolor='black', width=0.01,frac = 0.2, headwidth =4 , shrink = 0.01))


In [129]:
plt.annotate(
    '', xy=average_monthly,
    xycoords='data',
    xytext=[57000,0.58], textcoords='data',
    arrowprops= dict(facecolor='black', width=0.01,frac = 0.2, headwidth =4 , shrink = 0.01))


In [130]:
plt.annotate(
    '', xy=average_compensated,
    xycoords='data',
    xytext=[57000,0.58], textcoords='data',
    arrowprops= dict(facecolor='black', width=0.01,frac = 0.2, headwidth =4 , shrink = 0.01))


In [131]:
plt.text( 57000,0.55, u'2: average\n utility', weight = 'bold' )

In [132]:
plt.xlabel("Gross Income")
plt.ylabel("Utility")

In [114]:
image_path = "/Users/adrienpacifico/Dropbox/These_Pacifico/Adrien_Thesis_personal_docs/Latex_docs_whith_Git_versionning/Tax_temporality/programme/Theoreme_presentation/images/"
plt.savefig(image_path+"image_graph{}".format(3)); image_number+=1

In [239]:
plt.figure()

In [115]:
d = compensated_disposable_income
plot_line_between_points(first_point = (a[markers_on][0],d[0]), second_point =
                         (a[find_nearest(utility_vector, d[0])],d[0]))

In [116]:
plot_line_between_points(first_point = (a[markers_on][1],d[1]), second_point =
                         (a[find_nearest(utility_vector, d[1])],d[1]))

In [117]:
plot_line_between_points(first_point = (a[find_nearest(utility_vector, d[0])],d[0]), second_point =
                         (a[find_nearest(utility_vector, d[1])],d[1]))

In [118]:
#average utility on a montly basis with compensation

plt.plot(((np.array([a[find_nearest(utility_vector, d[0])],d[0]]) + np.array([a[find_nearest(utility_vector, d[1])],d[1]])) /2)[0],\
((np.array([a[find_nearest(utility_vector, d[0])],d[0]]) + np.array([a[find_nearest(utility_vector, d[1])],d[1]])) /2)[1], 'ro')

In [119]:
idx = find_nearest(utility_vector,((np.array([a[find_nearest(utility_vector, d[0])],d[0]]) + np.array([a[find_nearest(utility_vector, d[1])],d[1]])) /2)[1])
#plt.plot(a[idx],
#        utility_vector[idx], 'ko')

In [120]:
plot_line_between_points(first_point = (a[idx],utility_vector[idx]), 
                         second_point =
                         (((np.array([a[find_nearest(utility_vector, d[0])],d[0]]) + np.array([a[find_nearest(utility_vector, d[1])],d[1]])) /2)[0],\
                            ((np.array([a[find_nearest(utility_vector, d[0])],d[0]]) + np.array([a[find_nearest(utility_vector, d[1])],d[1]])) /2)[1]))

In [121]:
plt.grid()

In [122]:
#plt.plot((np.array([a[find_nearest(b, d[0])],d[0]]) + np.array([a[find_nearest(b, d[1])],d[1]])) /2 , 'ro')

In [123]:
z = np.array([a[find_nearest(utility_vector, d[0])],d[0]])

In [124]:
a[find_nearest(utility_vector, d[0])],d[0]

(29506, 0.52713755863655309)

In [125]:
np.array([a[find_nearest(utility_vector, d[1])],d[1]])

array([  7.66720000e+04,   8.57176529e-01])

In [126]:
np.array([a[find_nearest(utility_vector, d[0])],d[0]])

array([  2.95060000e+04,   5.27137559e-01])

In [127]:
plt.plot((np.array(
            ([a[find_nearest(utility_vector, d[1])],d[1]]) + np.array([a[find_nearest(utility_vector, d[0])],d[0]])/2)[1],
          ([a[find_nearest(utility_vector, d[1])],d[1]] + np.array([a[find_nearest(utility_vector, d[0])],d[0]]))/2)[0],
        'ro')

In [128]:
([a[find_nearest(utility_vector, d[1])],d[1]]) + np.array([a[find_nearest(utility_vector, d[0])],d[0]]))/2)

SyntaxError: invalid syntax (<ipython-input-128-9418a5dc326e>, line 1)

In [ ]:
plt.close()

In [129]:
#plt.plot(a[markers_on], c[markers_on],color='k',marker='o')

In [130]:
annual_average = a[(markers_on[0]+markers_on[1])/2], b[(markers_on[0]+markers_on[1])/2]
plt.plot(a[(markers_on[0]+markers_on[1])//2], 
         b[(markers_on[0]+markers_on[1])//2], 'bo')

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:1: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  if __name__ == '__main__':


NameError: name 'b' is not defined

In [ ]:
plot_line_between_points(monthly_average, annual_average)

In [131]:
plt.close()


In [132]:
a[markers_on].tolist()
[a[markers_on][0],
          a[markers_on][1],
         ]

[30000, 90000]

In [133]:
plt.plot([a[markers_on][0],
          a[markers_on][1],
         ],
         [b[markers_on][0],
          b[markers_on][1],
         ],
        )

NameError: name 'b' is not defined

In [134]:
plt.close()

In [135]:
plt.plot([1,3],[1,2],color='k',marker='o')

In [136]:
plt.plot([a[40000]], [a[40000],b[90000]], 'o')

NameError: name 'b' is not defined

In [ ]:
plt.plot([a[40000],b[40000]])

In [137]:

plt.plot(np.exp(np.arange(0,3,0.01))-1)
plt.plot(np.log(np.arange(1,10,0.02)))

In [138]:
plt.close()

In [139]:
math.exp(10)

22026.465794806718

In [140]:
np.exp(0)

1.0

In [141]:
xrange(0,10,0.1)

TypeError: integer argument expected, got float

In [ ]:
G(y) = ((0,1y)/y y)

$\alpha - \beta^{\frac{y}{\epsilon}}$

Où $\alpha$ est le taux maximal d'imposition, k le seuil contributif

In [ ]:
0.75 - 0.94**(1000/12000)

In [ ]:
def tax_func_1(income = None):
    return  (0.75 - 0.94**(income/12000))

In [ ]:
a = np.log(0.85)/ np.log(0.94)

In [ ]:
a*10000

In [ ]:
b = np.apply_along_axis(tax_func_1,0, a)

In [ ]:
plt.plot(b)

In [ ]:
math.log(beta) / math.log(alpha)

In [ ]:
alpha  = 0.60
beta = 0.5
seuil_non_contrib = 12000
k = (math.log(beta) / math.log(alpha))* seuil_non_contrib

def tax_func(income = None):
    return  ((alpha - beta**(income/k)))

In [ ]:
a = np.array(range(0,10**6))
b = np.apply_along_axis(tax_func,0, a)

In [ ]:
plt.plot(b)
#plt.xlim(0,100000)
#plt.ylim(-1000,3000)

In [ ]:
plt.close()

In [ ]:
def tax_func(income = None):
    return  (0.75 - 0.94**(income/15000))*income

In [ ]:
a = np.array(range(0,10**6))

In [ ]:
tax_func(400000)

In [ ]:
b = np.apply_along_axis(tax_func,0, a)

In [ ]:
plt.plot(b)
plt.xlim(0,50000)
plt.ylim(-10000,3000)

In [ ]:
plt.close()