In [1]:
%matplotlib qt

In [2]:
from __future__ import division
from matplotlib import pyplot as plt
import math
import numpy as np

In [3]:
def find_nearest(array,value):
    idx = (np.abs(array-value)).argmin()
    return idx

In [4]:
def find_nearests(array,values):
    idx = []
    for val in values:
        idx.append((np.abs(array-val)).argmin())
    return idx

In [5]:
def link_points_with_line(first_point = None, second_point = None):
    a = first_point[0] , second_point[0]
    b = first_point[1] , second_point[1]
    return a,b

def plot_line_between_points(first_point = None, second_point = None):
    link_points = link_points_with_line(first_point, second_point)
    return plt.plot(link_points[0], link_points[1])

In [6]:
plt.plot()

[]

In [7]:
%pylab

Using matplotlib backend: Qt4Agg
Populating the interactive namespace from numpy and matplotlib


In [8]:
plt.close()
#plt.plot([1,2],[1,2],color='k',marker='o')

## Une fonction convexe

In [9]:
def convex_tax_func(income = None):
    return  ((income/3150) **0.4)

In [10]:
a = np.array(range(0,10**5))
taxe_vector = np.apply_along_axis(convex_tax_func,0, a)

In [11]:
plt.plot(taxe_vector)

Two monthly wages :

In [12]:
markers_on = [30000, 90000 ]

In [13]:

plt.plot(a[markers_on], taxe_vector[markers_on], 'bo')



In [14]:
#averge tax on a monthly basis
plt.plot(a[markers_on].tolist()
         ,
         taxe_vector[markers_on].tolist()
         ,
        )

In [15]:
d = a[markers_on].sum()/2
e = taxe_vector[markers_on].sum()/2
monthly_average = d,e
plt.plot(d,e, 'ro')

In [16]:
#fist_point = [1,1]
#second_point = [3,3]
#plt.plot([1,3],[1,2],color='k',marker='o')

In [17]:
#plot_line_between_points(fist_point, second_point)

In [18]:
#link_points_with_line(fist_point, second_point)

In [19]:
middle = (taxe_vector[markers_on[0]]+taxe_vector[markers_on[1]])//2

In [20]:
#average tax on a annual one
plt.plot(a[(markers_on[0]+markers_on[1])//2], 
         taxe_vector[(markers_on[0]+markers_on[1])//2], 'bo')

In [21]:
annual_average = a[(markers_on[0]+markers_on[1])/2], taxe_vector[(markers_on[0]+markers_on[1])/2]
plot_line_between_points(monthly_average, annual_average)

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:1: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  if __name__ == '__main__':


In [22]:
(markers_on[0]+markers_on[1])/2

60000.0

### Lambda (compensation)

$\lambda$ s.t ...


$\lambda = \frac{G(2y_1)+G(2y_2)}{G(y_1+y_2)}$

In [23]:
def compensation(markers_on = None):
    return (
            (convex_tax_func(income = markers_on[0]) + convex_tax_func(income = markers_on[1]))
            / 
            (2*convex_tax_func(income = (markers_on[0]+markers_on[1])/2)))

In [24]:
compensation(markers_on)

0.9669686528899363

In [25]:
compensated_points = np.apply_along_axis(convex_tax_func,0, markers_on)/compensation(markers_on)

In [26]:
compensated_points

array([ 2.54748646,  3.95330559])

In [27]:
plt.plot(a[markers_on],compensated_points, 'ro')

In [28]:
plt.plot(a[markers_on], compensated_points)

In [29]:
np.apply_along_axis(convex_tax_func,0, markers_on)

array([ 2.46333955,  3.82272258])

In [30]:
plt.figure()

In [97]:
plt.close()

In [32]:
plt.figure()

## Utility function

In [33]:
def concave_u_func(income = None):
    return  (1 - 0.97**(income/1200))


#def concave_u_func(income = None):
#    return  income**0.4

In [34]:
def disposable_income(income = a):
    return a - np.apply_along_axis(convex_tax_func,0, a)

In [35]:
plt.plot([0,90000],[0,90000],color='k',marker='o')

In [36]:
plt.plot(a,disposable_income(a))

In [95]:
plt.close()
plt.figure()

In [90]:
a = np.array(range(0,10**5))
utility_vector = np.apply_along_axis(concave_u_func,0, a)
utility_disposable_income = np.apply_along_axis(concave_u_func,0, disposable_income(a))


In [91]:
plt.plot(a,utility_vector)

#gross income utility
plt.plot(a[markers_on], utility_vector[markers_on], 'bo')


In [92]:
#Taxed utility
plt.plot(a[markers_on], utility_disposable_income[markers_on], 'bo')


In [93]:
plot_line_between_points(first_point = (a[markers_on][0], utility_disposable_income[markers_on][0]), second_point = (a[markers_on][0], utility_vector[markers_on][0]))
plot_line_between_points(first_point = (a[markers_on][1], utility_disposable_income[markers_on][1]), second_point = (a[markers_on][1], utility_vector[markers_on][1]))

In [94]:
a_tax_util_index = np.array( [find_nearest(utility_vector,utility_disposable_income[markers_on][0]) , find_nearest(utility_vector,utility_disposable_income[markers_on][1] )])

In [43]:
#
plt.plot(a[a_tax_util_index] , utility_vector[a_tax_util_index] , 'bo')


In [44]:
plot_line_between_points(first_point = (a[markers_on][0], utility_disposable_income[markers_on][0]), second_point = (a[a_tax_util_index][0], utility_vector[a_tax_util_index][0])) # TODO: dashed line
plot_line_between_points(first_point = (a[markers_on][1], utility_disposable_income[markers_on][1]), second_point = (a[a_tax_util_index][1], utility_vector[a_tax_util_index][1])) # TODO: dashed line

In [45]:
a_tax_util_index

array([29998, 89996])

In [46]:
plt.plot(a[a_tax_util_index].tolist()
         ,
         utility_vector[a_tax_util_index].tolist()
         ,
        )

In [47]:
d = a[a_tax_util_index].sum()/2
e = utility_vector[a_tax_util_index].sum()/2
monthly_average = d,e
plt.plot(d,e, 'ro')

In [48]:
plt.plot(a[find_nearest(utility_vector,e)], utility_vector[find_nearest(utility_vector,e)], 'ro')

In [49]:
plot_line_between_points(first_point = (a[find_nearest(utility_vector,e)], utility_vector[find_nearest(utility_vector,e)]), 
                         second_point = (d,e))

In [50]:
d = a[markers_on].sum()/2
monthly_annual_tax = utility_vector[d]
monthly_d_income_a_t = a[markers_on] - monthly_annual_tax

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:2: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  from ipykernel import kernelapp as app


In [51]:
#b[60000]

In [52]:
#Annual après taxe
d = a[markers_on].sum()/2
monthly_annual_tax = taxe_vector[d]
monthly_d_income_a_t = a[markers_on] - monthly_annual_tax
monthly_u_a_t = utility_vector[find_nearests(a, monthly_d_income_a_t)]
plt.plot(a[markers_on][1],monthly_u_a_t[1], 'go')
plt.plot(a[markers_on][0],monthly_u_a_t[0], 'go')
#plt.plot(d[1],e[1], 'ro')

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:3: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  app.launch_new_instance()


In [53]:
#projection sur axe utilité
idx = find_nearests(a, monthly_d_income_a_t)
plt.plot(a[idx][0], utility_vector[idx][0], 'ro')
plt.plot(a[idx][1], utility_vector[idx][1], 'ro')





In [54]:
#line between points
plt.plot((a[idx][0] + a[idx][1])/2,
(utility_vector[idx][0] + utility_vector[idx][1])/2, 'ro')

In [55]:
plt.plot(a[find_nearest(utility_vector,(utility_vector[idx][0] + utility_vector[idx][1])/2)],
         utility_vector[42625],'ro')

In [56]:
#average
find_nearest(a,monthly_d_income_a_t.sum()/2)

59997

In [57]:
# Faire le find nearest sur la courbe d'utilité, faire utilité moyenne

In [58]:
monthly_u_a_t = utility_vector[find_nearests(a, monthly_d_income_a_t)]; monthly_u_a_t

array([ 0.53298973,  0.89816123])

In [59]:
find_nearest(a[markers_on], monthly_d_income_a_t)

0

In [60]:
#Annual après taxe
f = a[markers_on].sum()/2
g =  utility_disposable_income[d]
annual_average = d,e
plt.plot(f,g, 'ro')

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:3: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  app.launch_new_instance()


In [61]:
plot_line_between_points(first_point = (d,e), second_point = (f,g))


In [62]:
plt.plot(a[find_nearest(utility_vector,g)], utility_vector[find_nearest(utility_vector,g)], 'ro')

In [63]:
plot_line_between_points(first_point = (f,g), second_point =
                         (a[find_nearest(utility_vector,g)], utility_vector[find_nearest(utility_vector,g)]))

In [64]:
#utility loss without compensation


plot_line_between_points(first_point = , second_point = (f,g))







SyntaxError: invalid syntax (<ipython-input-64-8c7819a8e284>, line 4)

In [65]:
compensation(markers_on)

0.9669686528899363

In [66]:
compensated_points

array([ 2.54748646,  3.95330559])

In [67]:
find_nearest(a[markers_on], compensated_points[1])

0

In [68]:
plt.plot(a[13328],0,'yo')

In [69]:
d = np.apply_along_axis(concave_u_func, 0, a[markers_on] - compensated_points )

In [70]:
d

array([ 0.5329951 ,  0.89815877])

In [71]:
plt.plot(a[markers_on],d,'yo')

In [72]:
find_nearest(utility_vector, d[0])

29997

In [73]:
plt.plot(a[find_nearest(utility_vector, d[0])],d[0],'yo')
plt.plot(a[find_nearest(utility_vector, d[1])],d[1],'yo')

In [74]:
plot_line_between_points(first_point = (a[markers_on][0],d[0]), second_point =
                         (a[find_nearest(utility_vector, d[0])],d[0]))

In [75]:
plot_line_between_points(first_point = (a[markers_on][1],d[1]), second_point =
                         (a[find_nearest(utility_vector, d[1])],d[1]))

In [76]:
plot_line_between_points(first_point = (a[find_nearest(utility_vector, d[0])],d[0]), second_point =
                         (a[find_nearest(utility_vector, d[1])],d[1]))

In [77]:
#average utility on a montly basis with compensation

plt.plot(((np.array([a[find_nearest(utility_vector, d[0])],d[0]]) + np.array([a[find_nearest(utility_vector, d[1])],d[1]])) /2)[0],\
((np.array([a[find_nearest(utility_vector, d[0])],d[0]]) + np.array([a[find_nearest(utility_vector, d[1])],d[1]])) /2)[1], 'ro')

In [78]:
idx = find_nearest(utility_vector,((np.array([a[find_nearest(utility_vector, d[0])],d[0]]) + np.array([a[find_nearest(utility_vector, d[1])],d[1]])) /2)[1])
plt.plot(a[idx],
        utility_vector[idx], 'ko')

In [79]:
plot_line_between_points(first_point = (a[idx],utility_vector[idx]), 
                         second_point =
                         (((np.array([a[find_nearest(utility_vector, d[0])],d[0]]) + np.array([a[find_nearest(utility_vector, d[1])],d[1]])) /2)[0],\
                            ((np.array([a[find_nearest(utility_vector, d[0])],d[0]]) + np.array([a[find_nearest(utility_vector, d[1])],d[1]])) /2)[1]))

In [80]:
plt.grid()

In [81]:
#plt.plot((np.array([a[find_nearest(b, d[0])],d[0]]) + np.array([a[find_nearest(b, d[1])],d[1]])) /2 , 'ro')

In [82]:
z = np.array([a[find_nearest(utility_vector, d[0])],d[0]])

In [83]:
a[find_nearest(utility_vector, d[0])],d[0]

(29997, 0.53299509824366575)

In [84]:
np.array([a[find_nearest(utility_vector, d[1])],d[1]])

array([  8.99960000e+04,   8.98158767e-01])

In [85]:
np.array([a[find_nearest(utility_vector, d[0])],d[0]])

array([  2.99970000e+04,   5.32995098e-01])

In [86]:
plt.plot((np.array(
            ([a[find_nearest(utility_vector, d[1])],d[1]]) + np.array([a[find_nearest(utility_vector, d[0])],d[0]])/2)[1],
          ([a[find_nearest(utility_vector, d[1])],d[1]] + np.array([a[find_nearest(utility_vector, d[0])],d[0]]))/2)[0],
        'ro')

In [87]:
([a[find_nearest(utility_vector, d[1])],d[1]]) + np.array([a[find_nearest(utility_vector, d[0])],d[0]]))/2)

SyntaxError: invalid syntax (<ipython-input-87-9418a5dc326e>, line 1)

In [88]:
plt.close()

In [ ]:
#plt.plot(a[markers_on], c[markers_on],color='k',marker='o')

In [ ]:
annual_average = a[(markers_on[0]+markers_on[1])/2], b[(markers_on[0]+markers_on[1])/2]
plt.plot(a[(markers_on[0]+markers_on[1])//2], 
         b[(markers_on[0]+markers_on[1])//2], 'bo')

In [ ]:
plot_line_between_points(monthly_average, annual_average)

In [ ]:
plt.close()


In [ ]:
a[markers_on].tolist()
[a[markers_on][0],
          a[markers_on][1],
         ]

In [ ]:
plt.plot([a[markers_on][0],
          a[markers_on][1],
         ],
         [b[markers_on][0],
          b[markers_on][1],
         ],
        )

In [ ]:
plt.close()

In [ ]:
plt.plot([1,3],[1,2],color='k',marker='o')

In [ ]:
plt.plot([a[40000]], [a[40000],b[90000]], 'o')

In [ ]:
plt.plot([a[40000],b[40000]])

In [ ]:

plt.plot(np.exp(np.arange(0,3,0.01))-1)
plt.plot(np.log(np.arange(1,10,0.02)))

In [ ]:
plt.close()

In [ ]:
math.exp(10)

In [ ]:
np.exp(0)

In [ ]:
xrange(0,10,0.1)

In [ ]:
G(y) = ((0,1y)/y y)

$\alpha - \beta^{\frac{y}{\epsilon}}$

Où $\alpha$ est le taux maximal d'imposition, k le seuil contributif

In [ ]:
0.75 - 0.94**(1000/12000)

In [ ]:
def tax_func_1(income = None):
    return  (0.75 - 0.94**(income/12000))

In [ ]:
a = np.log(0.85)/ np.log(0.94)

In [ ]:
a*10000

In [ ]:
b = np.apply_along_axis(tax_func_1,0, a)

In [ ]:
plt.plot(b)

In [ ]:
math.log(beta) / math.log(alpha)

In [ ]:
alpha  = 0.60
beta = 0.5
seuil_non_contrib = 12000
k = (math.log(beta) / math.log(alpha))* seuil_non_contrib

def tax_func(income = None):
    return  ((alpha - beta**(income/k)))

In [ ]:
a = np.array(range(0,10**6))
b = np.apply_along_axis(tax_func,0, a)

In [ ]:
plt.plot(b)
#plt.xlim(0,100000)
#plt.ylim(-1000,3000)

In [ ]:
plt.close()

In [ ]:
def tax_func(income = None):
    return  (0.75 - 0.94**(income/15000))*income

In [ ]:
a = np.array(range(0,10**6))

In [ ]:
tax_func(400000)

In [ ]:
b = np.apply_along_axis(tax_func,0, a)

In [ ]:
plt.plot(b)
plt.xlim(0,50000)
plt.ylim(-10000,3000)

In [ ]:
plt.close()